site_name: Akari Records
nav:
  - Main Page: index.md
  - 'Japanese Guides':
    - Yomitan Configuration: jpguides/yomitan.md

plugins:
  - search

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg