site_name: Akari Records
site_url: https://example.com
site_author: Vladyslav Sorokin
nav:
  - Main Page: index.md
  - Japanese Guides:
    - Anki: jpguides/anki.md
    - Yomitan: jpguides/yomitan.md
  - Others:
    - Useful Links: others/links.md

plugins:
  - search
  #- social doesn't work properly on windows for some reason

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: yellow
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode

  #font:
    #text: Underdog
    #text: Roboto
    #text: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    #- navigation.tabs
    - navigation.sections
    #- navigation.path
    - toc.follow
    #- navigation.top
    - search.suggest

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - admonition
  
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences